import Footer from "@/components/footer/footer";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster";
import Providers from "@/context/reduxProvider";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const font = Nunito({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Alwan",
  description: "Generated by sazzad karim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={font.className}>
          <Header />
          {children}
          <Toaster />
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
