export enum tagTypes {
  auth = "auth",
  user = "user",
  product = "product",
  order = "order",
  feedback = "feedback",
  comment = "comment",
  coupon = "coupon",
  category = "category",
  address = "address",
  size = "size",
  carousel = "carousel",
  productType = "productType",
  color = "color",
}

export const tagTypeLists = [
  tagTypes.auth,
  tagTypes.user,
  tagTypes.product,
  tagTypes.order,
  tagTypes.feedback,
  tagTypes.comment,
  tagTypes.coupon,
  tagTypes.category,
  tagTypes.address,
  tagTypes.size,
  tagTypes.carousel,
  tagTypes.productType,
  tagTypes.color,
];
